---
version: 2.1

orbs:
  executor-tools: feedyard/executor-tools@dev:196a6b7
  #executor-tools: feedyard/executor-tools@0.3.0
  common: feedyard/common-pipeline-tasks@0.6.0

workflows:
  version: 2

  circleci-remote-docker-executor-pipeline:
    jobs:
      - executor-tools/dev-release:
          name: dev-release
          context: executor-publishing
          image: feedyard/circleci-remote-docker
          after-build:
            - run:
                name: configuration testing
                command: ash test.sh
          filters:
            branches:
              only: /master/
            tags:
              ignore: /.*/
      - executor-tools/publish:
          context: executor-publishing
          image: feedyard/circleci-remote-docker
          after-publish:
            - common/slack:
                title: New Executor Version
                message: new version published feedyard/circleci-remote-docker $CIRCLE_TAG
                webhook: SLACK_WEBHOOK
          clean-tags:
            - executor-tools/clean-docker-hub:
                image: feedyard/circleci-remote-docker
                registry-login: DOCKERLOGIN
                registry-password: DOCKERTOKEN
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

  # builds nightly from .unpinned Dockerfile in order to always be a latest base image and installed packages
  circleci-remote-docker-executor-nightly-build:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - executor-tools/dev-release:
          name: nightly-build
          context: executor-publishing
          image: feedyard/circleci-remote-docker
          dockerfile: Dockerfile.unpinned
          tag: nightly
          after-build:
            - run:
                name: configuration testing
                command: ash test_nightly.sh
