---
version: 2.1

orbs:
  executor-tools: feedyard/executor-tools@0.1.0
  common: feedyard/common-pipeline-tasks@0.3.0

workflows:
  version: 2

  circleci-remote-docker-executor-pipeline:
    jobs:
      - executor-tools/dev-release:
          context: executor-publishing
          image: feedyard/circleci-remote-docker
          registry: quay.io
          after-build:
            - run:
                name: configuration testing
                command: |
                  set -euo pipefail
                  inspec exec --no-distinct-exit profiles/cis-docker
                  CID="$(docker run -it -d --entrypoint ash quay.io/feedyard/circleci-remote-docker:$CIRCLE_SHA1)"
                  inspec exec profiles/circleci-remote-docker/ -t docker://$CID
                  docker rm -f $CID
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
      - executor-tools/publish:
          context: executor-publishing
          image: feedyard/circleci-remote-docker
          registry: quay.io
          after-publish:
            - common/slack:
                title: New Executor Version
                message: new version published feedyard/circleci-remote-docker $CIRCLE_TAG
                webhook: $SLACK_WEBHOOK
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

  # builds nightly from .unpinned Dockerfile in order to always be a latest for base image and packages
  circleci-remote-docker-executor-nightly-build:
    triggers:
      - schedule:
          cron: "0 0 1 * *"
          filters:
            branches:
              only: master
    jobs:
      - executor-tools/dev-release:
          context: executor-publishing
          image: feedyard/circleci-remote-docker
          tag: nightly
          registry: quay.io
          after-build:
            - run:
                name: configuration testing
                command: |
                  set -euo pipefail
                  inspec exec --no-distinct-exit profiles/cis-docker
                  CID="$(docker run -it -d --entrypoint ash quay.io/feedyard/circleci-remote-docker:nightly"
                  inspec exec profiles/circleci-remote-docker-unpinned/ -t docker://$CID
                  docker rm -f $CID
