---
version: 2.1

orbs:
  circle-agent: feedyard/circleci-agent-publish@dev:latest

workflows:
  circleci-remote-docker-image-pipeline:
    jobs:
      - circle-agent/dev-release:
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
      - circle-agent/publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
