version: 2

jobs:
  build:
    working_directory: ~/circleci-remote-docker
    environment:
      LIBRARY: feedyard
      CONTAINER_NAME: circleci-remote-docker
      VERSION: 3.6
      BASH_ENV: env
    docker:
      - image: feedyard/circleci-remote-docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: confirm Docker
          command: docker info
      - run:
          name: decrypt secrets
          command: openssl aes-256-cbc -d -in secrets.ci -out env -k $KEY
      - run:
          name: build image
          command: docker build -t $LIBRARY/$CONTAINER_NAME:latest .
      - run:
          name: tag with build version
          command: docker tag $LIBRARY/$CONTAINER_NAME:latest $LIBRARY/$CONTAINER_NAME:$VERSION.$CIRCLE_BUILD_NUM
      - run:
          name: configuration tests
          command: |
            inspec exec profiles/cis-docker
            CID="$(docker run -it -d $LIBRARY/$CONTAINER_NAME:latest ash)"
            inspec exec profiles/circleci-remote-docker/ -t docker://$CID
            docker rm -f $CID
      - deploy:
          name: deploy to docker hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $LIBRARY/$CONTAINER_NAME:$VERSION.$CIRCLE_BUILD_NUM
            docker push $LIBRARY/$CONTAINER_NAME:latest
