version: 2

jobs:
  build:
    working_directory: ~/circleci-remote-docker
    environment:
      LIBRARY: quay.io/feedyard
      CONTAINER_NAME: circleci-remote-docker
      VERSION: 3.8
      BASH_ENV: env
    docker:
      - image: feedyard/circleci-remote-docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: confirm Docker
          command: docker info
      - run:
          name: decrypt secrets
          # command: invoke dec
          command: openssl aes-256-cbc -d -in env.ci -out local.env -k $FEEDYARD_PIPELINE_KEY
      - run:
          name: build image
          command: docker build -t $LIBRARY/$CONTAINER_NAME:latest .
      - run:
          name: tag with build version
          command: docker tag $LIBRARY/$CONTAINER_NAME:latest $LIBRARY/$CONTAINER_NAME:$VERSION.$CIRCLE_BUILD_NUM
      - run:
          name: configuration tests
          command: |
            set -euo pipefail
            CID="$(docker run -it -d --entrypoint ash $LIBRARY/$CONTAINER_NAME:latest)"
            inspec exec profiles/circleci-remote-docker/ -t docker://$CID
            docker rm -f $CID
      - deploy:
          name: deploy to docker hub
          command: |
            docker login -u=$FEEDYARD_CIRCLECI_QUAYIO_DEPLOY_USER -p=$FEEDYARD_CIRCLECI_QUAYIO_DEPLOY_USER_TOKEN quay.io
            docker push $LIBRARY/$CONTAINER_NAME:$VERSION.$CIRCLE_BUILD_NUM
            docker push $LIBRARY/$CONTAINER_NAME:latest
